### ISSUE TITLE
Admin user can delete himself when there are no other admin users

### ISSUE THREAD

**Issue by SorJEF** [devicehive/devicehive-java-server#105]
Admin user can delete himself from the admin UI when there are no other admin users.

I think expected behavior would be returning a "bad request" error when the API call is executed in such a case.

**Comment by demon-xxi** [comment]
Wow, this looks like a very rare case. I would not mark it as a bug specifically. It is a foolproof enhancement I think.  
Let's make it a lo priority ticket.

**Comment by Nikolay-Kha** [comment]
And you also can delete default access key in playground. And after it your playground will be broken :) Next log in attempt through - "Can't create and init a User"

**Comment by demon-xxi** [comment]
This one I'm going to address. The playground should recreate key if it's missing.

**Comment by mdolbin** [comment]
@SorJEF @demon-xxi @Nikolay-Kha @zubrabubra 
Hello, guys. I believe we should forbid users to delete themselves and their last default (means token type here, not token, initially created by playground) access token instead of recreating it.

Admin console does not require particular access token to authenticate but it needs at least one access token of default type with any set of permissions to authenticate user.

I implemented the following logic:
(*current something* means an entity used to authenticate request)
* Deleting current user is forbidden
* Deleting owner of current access token is forbidden
* Deleting the last default access token of current user or someone else is forbidden, even for Admin role
* Default access token can be deleted if its owner has at least 2 default access tokens

One of the following messages with HTTP code 403 is returned if user encounters these constraints:
* You can not delete current user or owner of current access key
* You can not delete your last default access key

I covered these changes and some related logic with [mocha tests](https://github.com/devicehive/devicehive-tests).

I think we should also hide \ disable "Delete" button in admin console if user has 1 access token in total. 

Please, let me know if you have any objections or suggestions regarding this solution.
