### ISSUE TITLE
Polling command after ts should return any messages

### ISSUE THREAD

**Issue by zubrabubra** [devicehive/devicehive-java-server#119]
Polling returns stored commands only if they have isUpdated flag set to true, while leaving initial(isUpdated=false) commands in buffer; making impossible to fetch messages received between polling request re-instantiation.

**Comment by mdolbin** [comment]
Discussion notes (@mdolbin, @zubrabubra, @Nikolay-Kha):
Poll endpoints:
/{deviceGuid}/command/poll
/command/poll
**should:**
* Return commands with timestamps *greater* than passed
* Return commands without device response (not updated commands)

**Keep in mind \ Discuss later:**
* In case of long polling we should return all concurrent commands with the same timestamp instead of the first one
* Кeturn up to `maxCount` commands if `maxCount` querystring parameter is passed


/{deviceGuid}/command/{commandId}/poll
**should:**
* Return updated command or wait for it update up to passed `waitTimeout` parameter \ default timeout value
* Return empty response at the end of the polling session if the requested command was not updated yet
* If updated command is polled, it should be returned immidiately instead of waiting for one more update
