### ISSUE TITLE
device register without/with access key

### ISSUE THREAD

**Issue by Pilatuz** [devicehive/devicehive-java-server#121]
There is something strange with device registration procedure.

If I'm trying to register device without access key:

`curl -X PUT -H "Content-Type: application/json" -d '{"name" : "name", "deviceClass": {"name" : "default device", "version": "1.0"}}' 'http://playground.devicehive.com/api/rest/device/test-name'`

server returns `401 - Unauthorized` as expected, BUT once I added valid access key (remaining request is the same):

`curl -X PUT -H "Authorization: Bearer gfgCKy2KNC+MMuiwTKRTcqEPLv84gEEh9b26lQOZTq5=" -H "Content-Type: application/json" -d '{"name" : "name", "deviceClass": {"name" : "default device", "version": "1.0"}}' 'http://playground.devicehive.com/api/rest/device/test-name'`

the server still returns the 401 status. Json response now contains: `{
  "error": 401,
  "message": "Device with such guid = test-name not found"
}`

If the device guid is changed to another value:

`curl -X PUT -H "Authorization: Bearer gfgCKy2KNC+MMuiwTKRTcqEPLv84gEEh9b26lQOZTq5=" -H "Content-Type: application/json" -d '{"name" : "name", "deviceClass": {"name" : "default device", "version": "1.0"}}' 'http://playground.devicehive.com/api/rest/device/test-name1'`

everything is OK.

Moreover, sometimes if I remove the access key again, server returns 204 status but device is not actually created. Perhaps there is something wrong with access key caching...

**Comment by zubrabubra** [comment]
```curl -X PUT -H "Content-Type: application/json" -d '{"name" : "name", "deviceClass": {"name" : "default device", "version": "1.0"}}' 'http://playground.devicehive.com/api/rest/device/test-name'```
is executed first time with response 204 and then one get 401 because anonymous user has no access to the device (device is not in network, key for the device is not specified), actually consequent calls are treated as an update attempt.

Again even when header with bearer code specified - no access to the device.

Suppose we need to return different error codes when update request issued and current user has no access to the device (403 instead of 401, even if current user is anonymous).
